# Testingflag
testing: True
# path to samples
samples: /home/fp5-ws18/data/samples.tsv
# path to reference
reference: /home/fp5-ws18/data/homo_sapiens_transcriptome.fa.gz
gtfReference: /home/fp5-ws18/data/homo_sapiens_transcriptome.gtf.gz
#kallisto index flag and path to kallistoIndex (if flag True)
indexFlag: True
indexPath: /home/fp5-ws18/data/homo_sapiens_transcriptome.idx
